zabbix_export:
  version: '5.2'
  date: '2021-09-07T04:46:33Z'
  groups:
    -
      name: 'Zabbix servers'
  templates:
    -
      template: 'Zabbix Mysql Backup'
      name: 'Zabbix Mysql Backup'
      groups:
        -
          name: 'Zabbix servers'
      items:
        -
          name: 'Backup checksum'
          key: 'vfs.file.cksum[/var/lib/mysql/backup_zabbix.log]'
          delay: '60s;0/1-7,00:00-06:00;0/1-7,06:01-24:00'
        -
          name: 'Backup status'
          key: 'vfs.file.regmatch[/var/lib/mysql/backup_zabbix.log,Status = OK]'
          delay: '60s;0/1-7,00:00-06:00;0/1-7,06:01-24:00'
  triggers:
    -
      expression: |
        {Zabbix Mysql Backup:vfs.file.cksum[/var/lib/mysql/backup_zabbix.log].change()}=0
        or
        {Zabbix Mysql Backup:vfs.file.regmatch[/var/lib/mysql/backup_zabbix.log,Status = OK].last()}=0
      name: 'Zabbix database backup fail'
      priority: HIGH
