- hosts: active
  become: yes
  tasks:
    - name: "Configure Zabbix Server SSHKeyLocation"
      lineinfile:
        dest=/etc/zabbix/zabbix_server.conf
        regexp='^# SSHKeyLocation='
        line="SSHKeyLocation=/var/lib/mysql/MC/.ssh"
        state=present
