- hosts: active
  become: yes
  tasks:
    - name: Download pre UrBackup job script
      get_url:
        url: "{{ git_source }}/mssql/scripts/prefilebackup"
        dest: /usr/local/etc/urbackup/
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: change pre UrBackup job script permission
      file:
        path: /usr/local/etc/urbackup/prefilebackup
        state: touch
        mode: "u+rwx,g-rwx,o-rwx"
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: Download post UrBackup job script
      get_url:
        url: "{{ git_source }}/mssql/scripts/postfilebackup"
        dest: /usr/local/etc/urbackup/
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"

    - name: change post UrBackup job script permission
      file:
        path: /usr/local/etc/urbackup/postfilebackup
        state: touch
        mode: "u+rwx,g-rwx,o-rwx"
      when: lb_primary == "yes"
      with_items: "{{ lb_primary | default([]) }}"
