#https://bestmonitoringtools.com/how-to-install-zabbix-server-on-ubuntu/
- hosts: active
  become: yes
  tasks:
    - name: "apt update"
      apt:
       update_cache: true

#    - name: Install package qemu-kvm (qemu-system-arm --> ubuntu 22)
#      apt:
#       name: qemu-system-arm
#       state: present

    - name: Install package qemu-kvm
      apt:
       name: qemu-kvm
       state: present
    
    - name: Install package libvirt-clients
      apt:
       name: libvirt-clients
       state: present

    - name: Install package libvirt-daemon-system
      apt:
       name: libvirt-daemon-system
       state: present

    - name: Install package bridge-utils
      apt:
       name: bridge-utils
       state: present

    - name: Install package virtinst
      apt:
       name: virtinst
       state: present

    - name: Install package libvirt-daemon
      apt:
       name: libvirt-daemon
       state: present

    - name: Install package virt-manager
      apt:
       name: virt-manager
       state: present

    - name: Install package libosinfo-bin
      apt:
       name: libosinfo-bin
       state: present

    - name: Install package libguestfs-tools
      apt:
       name: libguestfs-tools
       state: present
